//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.smartid {

public class ImageField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ImageField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ImageField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ImageField() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csSmartIdEnginePINVOKE.delete_ImageField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public ImageField() : this(csSmartIdEnginePINVOKE.new_ImageField__SWIG_0(), true) {
  }

  public ImageField(string name, Image value, bool is_accepted, double confidence) : this(csSmartIdEnginePINVOKE.new_ImageField__SWIG_1(name, Image.getCPtr(value), is_accepted, confidence), true) {
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public string GetName() {
    string ret = csSmartIdEnginePINVOKE.ImageField_GetName(swigCPtr);
    return ret;
  }

  public Image GetValue() {
    Image ret = new Image(csSmartIdEnginePINVOKE.ImageField_GetValue(swigCPtr), false);
    return ret;
  }

  public bool IsAccepted() {
    bool ret = csSmartIdEnginePINVOKE.ImageField_IsAccepted(swigCPtr);
    return ret;
  }

  public double GetConfidence() {
    double ret = csSmartIdEnginePINVOKE.ImageField_GetConfidence(swigCPtr);
    return ret;
  }

}

}
