//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.smartid {

public class RecognitionSession : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RecognitionSession(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RecognitionSession obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~RecognitionSession() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csSmartIdEnginePINVOKE.delete_RecognitionSession(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual RecognitionResult ProcessSnapshot(byte[] data, uint data_length, int width, int height, int stride, int channels, Rectangle roi, ImageOrientation image_orientation) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessSnapshot__SWIG_0(swigCPtr, data, data_length, width, height, stride, channels, Rectangle.getCPtr(roi), (int)image_orientation), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessSnapshot(byte[] data, uint data_length, int width, int height, int stride, int channels, Rectangle roi) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessSnapshot__SWIG_1(swigCPtr, data, data_length, width, height, stride, channels, Rectangle.getCPtr(roi)), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessSnapshot(byte[] data, uint data_length, int width, int height, int stride, int channels, ImageOrientation image_orientation) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessSnapshot__SWIG_2(swigCPtr, data, data_length, width, height, stride, channels, (int)image_orientation), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessSnapshot(byte[] data, uint data_length, int width, int height, int stride, int channels) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessSnapshot__SWIG_3(swigCPtr, data, data_length, width, height, stride, channels), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessYUVSnapshot(byte[] yuv_data, uint yuv_data_length, int width, int height, Rectangle roi, ImageOrientation image_orientation) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessYUVSnapshot__SWIG_0(swigCPtr, yuv_data, yuv_data_length, width, height, Rectangle.getCPtr(roi), (int)image_orientation), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessYUVSnapshot(byte[] yuv_data, uint yuv_data_length, int width, int height, Rectangle roi) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessYUVSnapshot__SWIG_1(swigCPtr, yuv_data, yuv_data_length, width, height, Rectangle.getCPtr(roi)), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessYUVSnapshot(byte[] yuv_data, uint yuv_data_length, int width, int height, ImageOrientation image_orientation) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessYUVSnapshot__SWIG_2(swigCPtr, yuv_data, yuv_data_length, width, height, (int)image_orientation), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessYUVSnapshot(byte[] yuv_data, uint yuv_data_length, int width, int height) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessYUVSnapshot__SWIG_3(swigCPtr, yuv_data, yuv_data_length, width, height), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessImage(Image image, Rectangle roi, ImageOrientation image_orientation) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessImage__SWIG_0(swigCPtr, Image.getCPtr(image), Rectangle.getCPtr(roi), (int)image_orientation), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessImage(Image image, Rectangle roi) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessImage__SWIG_1(swigCPtr, Image.getCPtr(image), Rectangle.getCPtr(roi)), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessImage(Image image, ImageOrientation image_orientation) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessImage__SWIG_2(swigCPtr, Image.getCPtr(image), (int)image_orientation), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessImage(Image image) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessImage__SWIG_3(swigCPtr, Image.getCPtr(image)), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessImageFile(string image_file, Rectangle roi, ImageOrientation image_orientation) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessImageFile__SWIG_0(swigCPtr, image_file, Rectangle.getCPtr(roi), (int)image_orientation), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessImageFile(string image_file, Rectangle roi) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessImageFile__SWIG_1(swigCPtr, image_file, Rectangle.getCPtr(roi)), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessImageFile(string image_file, ImageOrientation image_orientation) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessImageFile__SWIG_2(swigCPtr, image_file, (int)image_orientation), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessImageFile(string image_file) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessImageFile__SWIG_3(swigCPtr, image_file), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void Reset() {
    csSmartIdEnginePINVOKE.RecognitionSession_Reset(swigCPtr);
  }

}

}
