//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.smartid {

public class OcrCharVariant : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OcrCharVariant(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(OcrCharVariant obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~OcrCharVariant() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csSmartIdEnginePINVOKE.delete_OcrCharVariant(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public OcrCharVariant() : this(csSmartIdEnginePINVOKE.new_OcrCharVariant__SWIG_0(), true) {
  }

  public OcrCharVariant(ushort utf16_char, double confidence) : this(csSmartIdEnginePINVOKE.new_OcrCharVariant__SWIG_1(utf16_char, confidence), true) {
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public OcrCharVariant(string utf8_char, double confidence) : this(csSmartIdEnginePINVOKE.new_OcrCharVariant__SWIG_2(utf8_char, confidence), true) {
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public ushort GetUtf16Character() {
    ushort ret = csSmartIdEnginePINVOKE.OcrCharVariant_GetUtf16Character(swigCPtr);
    return ret;
  }

  public string GetUtf8Character() {
    string ret = csSmartIdEnginePINVOKE.OcrCharVariant_GetUtf8Character(swigCPtr);
    return ret;
  }

  public double GetConfidence() {
    double ret = csSmartIdEnginePINVOKE.OcrCharVariant_GetConfidence(swigCPtr);
    return ret;
  }

}

}
